version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: webflux-coroutine-sample-mysql
    command:
      - --max_connections=1000
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
      - MYSQL_USER=bacto
      - MYSQL_PASSWORD=bactopass
      - MYSQL_DATABASE=webflux
      - TZ=Asia/Seoul
